//! Dev-only: bake a printable-ASCII (0x20..=0x7E) SDF glyph atlas from a
//! monospace TTF into `<out>.bin` (raw R8 atlas) + `<out>.rs` (consts +
//! `include_bytes!`) for ricom's `backend-gl` text engine. Not part of the
//! workspace build. Usage:
//!   cargo run --release --manifest-path tools/gen-sdf-atlas/Cargo.toml -- \
//!       <font.ttf> <out-stem>
//!
//! Each glyph is rasterised at `RASTER_PX`, placed into a fixed square cell at a
//! common baseline (so the renderer can tile cells by ASCII index with a fixed
//! monospace advance), converted to a signed distance field, and packed into a
//! COLS×ROWS grid. Inside > 0.5, edge = 0.5, so the shader thresholds at 0.5.

use std::fs;

use fontdue::{Font, FontSettings};

const FIRST: u8 = 0x20;
const LAST: u8 = 0x7E;
const COUNT: usize = (LAST - FIRST + 1) as usize; // 95 printable glyphs
const COLS: usize = 16;
const ROWS: usize = COUNT.div_ceil(COLS); // 6
const CELL: usize = 48; // atlas cell, square (px)
const PAD: i32 = 6; // border inside the cell (>= SPREAD) so the SDF has room
const RASTER_PX: f32 = 36.0; // glyph raster size; CELL - 2*PAD
const SPREAD: f32 = 6.0; // distance (cell px) mapped across the 0..1 SDF range

fn main() {
    let mut args = std::env::args().skip(1);
    let font_path = args.next().unwrap_or_else(|| {
        "/usr/share/fonts/liberation-mono/LiberationMono-Regular.ttf".into()
    });
    let out_stem = args.next().unwrap_or_else(|| "glyphs".into());

    let bytes = fs::read(&font_path).expect("read font file");
    let font = Font::from_bytes(bytes.as_slice(), FontSettings::default()).expect("parse font");

    let lm = font.horizontal_line_metrics(RASTER_PX).expect("horizontal line metrics");
    let baseline: i32 = PAD + lm.ascent.round() as i32; // cell-y of the baseline
    // Monospace: every advance is equal; take a reference glyph.
    let advance_px = font.metrics('M', RASTER_PX).advance_width;

    let atlas_w = COLS * CELL;
    let atlas_h = ROWS * CELL;
    let mut atlas = vec![0u8; atlas_w * atlas_h];

    for i in 0..COUNT {
        let ch = (FIRST + i as u8) as char;
        let (m, cov) = font.rasterize(ch, RASTER_PX);

        // Blit the coverage into a CELL×CELL buffer at the glyph's cell position.
        let mut cell = vec![0.0f32; CELL * CELL];
        let gx = PAD + m.xmin; // left edge (xmin is the left bearing, may be < 0)
        let gy = baseline - (m.ymin + m.height as i32); // top edge, from the baseline
        for row in 0..m.height {
            for col in 0..m.width {
                let cx = gx + col as i32;
                let cy = gy + row as i32;
                if cx < 0 || cy < 0 || cx as usize >= CELL || cy as usize >= CELL {
                    continue; // clip anything outside the cell
                }
                cell[cy as usize * CELL + cx as usize] = cov[row * m.width + col] as f32 / 255.0;
            }
        }

        let sdf = signed_distance_field(&cell, CELL, CELL, SPREAD);

        // Pack into the atlas grid.
        let (col0, row0) = ((i % COLS) * CELL, (i / COLS) * CELL);
        for cy in 0..CELL {
            let dst = (row0 + cy) * atlas_w + col0;
            atlas[dst..dst + CELL].copy_from_slice(&sdf[cy * CELL..cy * CELL + CELL]);
        }
    }

    let bin_path = format!("{out_stem}.bin");
    let rs_path = format!("{out_stem}.rs");
    fs::write(&bin_path, &atlas).expect("write atlas .bin");

    let bin_name = std::path::Path::new(&bin_path)
        .file_name()
        .unwrap()
        .to_string_lossy();
    let rs = format!(
        "//! @generated by tools/gen-sdf-atlas from {font} — do not edit by hand.\n\
         //! Printable-ASCII ({first:#04x}..={last:#04x}) signed-distance-field glyph atlas.\n\
         #![cfg_attr(rustfmt, rustfmt::skip)]\n\
         /// Atlas width/height in texels (single-channel R8).\n\
         pub const ATLAS_W: usize = {atlas_w};\n\
         pub const ATLAS_H: usize = {atlas_h};\n\
         /// Square cell size (px) and grid layout.\n\
         pub const CELL: usize = {cell};\n\
         pub const COLS: usize = {cols};\n\
         pub const ROWS: usize = {rows};\n\
         /// First/last codepoint covered (contiguous).\n\
         pub const FIRST: u8 = {first:#04x};\n\
         pub const LAST: u8 = {last:#04x};\n\
         /// A cell drawn at `px * CELL_OVER_RASTER` shows a glyph of height ~`px`.\n\
         pub const CELL_OVER_RASTER: f32 = {cor:?};\n\
         /// Monospace advance as a fraction of `px` (pen step = `px * ADVANCE`).\n\
         pub const ADVANCE: f32 = {adv:?};\n\
         /// Row-major R8 SDF texels, `ATLAS_W * ATLAS_H` bytes.\n\
         pub static ATLAS: &[u8] = include_bytes!(\"{bin}\");\n",
        font = font_path,
        first = FIRST,
        last = LAST,
        atlas_w = atlas_w,
        atlas_h = atlas_h,
        cell = CELL,
        cols = COLS,
        rows = ROWS,
        cor = CELL as f32 / RASTER_PX,
        adv = advance_px / RASTER_PX,
        bin = bin_name,
    );
    fs::write(&rs_path, rs).expect("write glyphs .rs");

    eprintln!(
        "wrote {bin_path} ({atlas_w}x{atlas_h} R8, {} bytes) and {rs_path} for {COUNT} glyphs",
        atlas.len()
    );
}

/// Signed distance field of a coverage buffer: for each pixel, the Euclidean
/// distance (cell px) to the nearest pixel of the opposite class (inside if
/// coverage >= 0.5), signed positive inside, encoded to `0..=255` with `0.5` at
/// the edge over `±SPREAD`. Brute force — cells are tiny and this runs once.
fn signed_distance_field(cov: &[f32], w: usize, h: usize, spread: f32) -> Vec<u8> {
    let inside: Vec<bool> = cov.iter().map(|&c| c >= 0.5).collect();
    let mut out = vec![0u8; w * h];
    for y in 0..h {
        for x in 0..w {
            let here = inside[y * w + x];
            let mut best = f32::INFINITY;
            for yy in 0..h {
                for xx in 0..w {
                    if inside[yy * w + xx] != here {
                        let dx = x as f32 - xx as f32;
                        let dy = y as f32 - yy as f32;
                        best = best.min(dx * dx + dy * dy);
                    }
                }
            }
            let dist = best.sqrt(); // +inf if no opposite pixel exists (e.g. space)
            let signed = if here { dist } else { -dist };
            let v = 0.5 + signed / (2.0 * spread);
            out[y * w + x] = (v.clamp(0.0, 1.0) * 255.0).round() as u8;
        }
    }
    out
}
