//! @generated by tools/gen-sdf-atlas from /usr/share/fonts/liberation-mono/LiberationMono-Regular.ttf — do not edit by hand.
//! Printable-ASCII (0x20..=0x7e) signed-distance-field glyph atlas.
#![cfg_attr(rustfmt, rustfmt::skip)]
/// Atlas width/height in texels (single-channel R8).
pub const ATLAS_W: usize = 768;
pub const ATLAS_H: usize = 288;
/// Square cell size (px) and grid layout.
pub const CELL: usize = 48;
pub const COLS: usize = 16;
pub const ROWS: usize = 6;
/// First/last codepoint covered (contiguous).
pub const FIRST: u8 = 0x20;
pub const LAST: u8 = 0x7e;
/// A cell drawn at `px * CELL_OVER_RASTER` shows a glyph of height ~`px`.
pub const CELL_OVER_RASTER: f32 = 1.3333334;
/// Monospace advance as a fraction of `px` (pen step = `px * ADVANCE`).
pub const ADVANCE: f32 = 0.60009766;
/// Row-major R8 SDF texels, `ATLAS_W * ATLAS_H` bytes.
pub static ATLAS: &[u8] = include_bytes!("glyphs.bin");
