//! General SDF text renderer: draws arbitrary printable-ASCII strings on the
//! overlay from an embedded signed-distance-field glyph atlas (see [`crate::glyphs`],
//! generated by `tools/gen-sdf-atlas`). Not FPS-specific — any feature can draw
//! text (labels, notifications, HUDs). Crisp at any size thanks to SDF `smoothstep`
//! anti-aliasing; no runtime font dependency.
//!
//! Reuses the backend's unit-quad VAO and `BLIT_VS` (position via `u_rect`/`u_screen`),
//! so [`TextRenderer::draw`] assumes the caller has that VAO bound and premultiplied
//! blending enabled — exactly the state inside `GlBackend::present_windows`.

use anyhow::{anyhow, Result};
use glow::HasContext as _;

use crate::{glyphs, make_program, BLIT_VS};

/// Fragment shader: sample the SDF atlas sub-rect and threshold at 0.5 with a
/// screen-space (`fwidth`) anti-alias band. Emits premultiplied alpha to match the
/// `ONE, ONE_MINUS_SRC_ALPHA` blend the compositor uses.
const SDF_FS: &str = r#"#version 330 core
in vec2 v_tex;
uniform sampler2D u_atlas;
uniform vec4 u_uv;      // atlas sub-rect: xy = origin, zw = size (0..1)
uniform vec4 u_color;   // straight RGBA
out vec4 frag;
void main() {
    vec2 uv = u_uv.xy + v_tex * u_uv.zw;
    float d = texture(u_atlas, uv).r;      // 0.5 = glyph edge, > 0.5 inside
    float aa = fwidth(d);
    float a = smoothstep(0.5 - aa, 0.5 + aa, d) * u_color.a;
    frag = vec4(u_color.rgb * a, a);
}
"#;

/// Draws strings from the embedded SDF atlas. Owns its GLSL program + atlas
/// texture; positioning uniforms are set per glyph.
pub struct TextRenderer {
    program: glow::NativeProgram,
    atlas: glow::NativeTexture,
    u_screen: Option<glow::NativeUniformLocation>,
    u_rect: Option<glow::NativeUniformLocation>,
    u_uv: Option<glow::NativeUniformLocation>,
    u_color: Option<glow::NativeUniformLocation>,
    u_atlas: Option<glow::NativeUniformLocation>,
}

impl TextRenderer {
    /// Compile the SDF program and upload the glyph atlas (once). Requires a
    /// current GL context (the caller is inside the backend's context).
    pub fn new(gl: &glow::Context) -> Result<Self> {
        let program = make_program(gl, BLIT_VS, SDF_FS)?;
        let (atlas, u_screen, u_rect, u_uv, u_color, u_atlas) = unsafe {
            let atlas = gl.create_texture().map_err(|e| anyhow!("text atlas texture: {e}"))?;
            gl.bind_texture(glow::TEXTURE_2D, Some(atlas));
            gl.pixel_store_i32(glow::UNPACK_ALIGNMENT, 1); // single-channel rows
            gl.tex_image_2d(
                glow::TEXTURE_2D, 0, glow::R8 as i32,
                glyphs::ATLAS_W as i32, glyphs::ATLAS_H as i32, 0,
                glow::RED, glow::UNSIGNED_BYTE,
                glow::PixelUnpackData::Slice(Some(glyphs::ATLAS)),
            );
            gl.tex_parameter_i32(glow::TEXTURE_2D, glow::TEXTURE_MIN_FILTER, glow::LINEAR as i32);
            gl.tex_parameter_i32(glow::TEXTURE_2D, glow::TEXTURE_MAG_FILTER, glow::LINEAR as i32);
            gl.tex_parameter_i32(glow::TEXTURE_2D, glow::TEXTURE_WRAP_S, glow::CLAMP_TO_EDGE as i32);
            gl.tex_parameter_i32(glow::TEXTURE_2D, glow::TEXTURE_WRAP_T, glow::CLAMP_TO_EDGE as i32);
            gl.bind_texture(glow::TEXTURE_2D, None);
            (
                atlas,
                gl.get_uniform_location(program, "u_screen"),
                gl.get_uniform_location(program, "u_rect"),
                gl.get_uniform_location(program, "u_uv"),
                gl.get_uniform_location(program, "u_color"),
                gl.get_uniform_location(program, "u_atlas"),
            )
        };
        Ok(TextRenderer { program, atlas, u_screen, u_rect, u_uv, u_color, u_atlas })
    }

    /// On-screen size of `s` at glyph height `px`: `(width, height)` in pixels.
    /// Monospace, so width scales with the character count.
    pub fn measure(&self, px: f32, s: &str) -> (f32, f32) {
        let n = s.chars().count() as f32;
        (n * px * glyphs::ADVANCE, px * glyphs::CELL_OVER_RASTER)
    }

    /// Draw `s` with its top-left at (`x`, `y`), glyphs `px` tall, in `color`
    /// (straight RGBA). Assumes the unit-quad VAO is bound and premultiplied-alpha
    /// blending is enabled (as in `present_windows`). Non-printable chars advance
    /// the pen without drawing.
    #[allow(clippy::too_many_arguments)]
    pub fn draw(
        &self,
        gl: &glow::Context,
        screen_w: i32,
        screen_h: i32,
        x: f32,
        y: f32,
        px: f32,
        color: [f32; 4],
        s: &str,
    ) {
        let cell = px * glyphs::CELL_OVER_RASTER; // on-screen cell size (square)
        let advance = px * glyphs::ADVANCE;
        let uw = glyphs::CELL as f32 / glyphs::ATLAS_W as f32; // atlas cell uv size
        let uh = glyphs::CELL as f32 / glyphs::ATLAS_H as f32;
        unsafe {
            gl.use_program(Some(self.program));
            gl.active_texture(glow::TEXTURE0);
            gl.bind_texture(glow::TEXTURE_2D, Some(self.atlas));
            gl.uniform_1_i32(self.u_atlas.as_ref(), 0);
            gl.uniform_2_f32(self.u_screen.as_ref(), screen_w as f32, screen_h as f32);
            gl.uniform_4_f32(self.u_color.as_ref(), color[0], color[1], color[2], color[3]);
            let mut pen = x;
            for ch in s.chars() {
                let c = ch as u32;
                if (glyphs::FIRST as u32..=glyphs::LAST as u32).contains(&c) && ch != ' ' {
                    let idx = (c - glyphs::FIRST as u32) as usize;
                    let (col, row) = (idx % glyphs::COLS, idx / glyphs::COLS);
                    gl.uniform_4_f32(self.u_uv.as_ref(), col as f32 * uw, row as f32 * uh, uw, uh);
                    gl.uniform_4_f32(self.u_rect.as_ref(), pen, y, cell, cell);
                    gl.draw_arrays(glow::TRIANGLE_STRIP, 0, 4);
                }
                pen += advance;
            }
        }
    }
}
